var name;function statusChangeCallback(response){console.log('statusChangeCallback');console.log(response);if(response.status==='connected'){getFBID(response);testAPI();autoriseeritus('connected');}else if(response.status==='not_authorized'){document.getElementById('status').innerHTML='Palun logi sisse ';autoriseeritus('not_authorized');}else{document.getElementById('status').innerHTML='Palun logi sisse';autoriseeritus('not_loggedin');}}
function checkLoginState(){FB.getLoginStatus(function(response){statusChangeCallback(response);});}
window.fbAsyncInit=function(){FB.init({appId:'365096093614947',cookie:true,xfbml:true,version:'v2.2'});FB.getLoginStatus(function(response){statusChangeCallback(response);});};(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/et_EE/sdk.js";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));function testAPI(){console.log('Welcome!  Fetching your information.... ');FB.api('/me',function(response){console.log('Successful login for: '+response.name);document.getElementById('status').innerHTML='Tere, '+response.name+'!';name=response.name;});}
function autoriseeritus(status){if(status=='connected'){document.getElementById("juhis").innerHTML="Siin saad lisada lehele uue kandidaadi";document.getElementById("invite").style.visibility="visible";}
if(status=='not_loggedin'){document.getElementById("juhis").innerHTML="Uue kandidaadi lisamiseks logi sisse";document.getElementById("invite").style.visibility="hidden";}
if(status=='not_loggedin'){document.getElementById("juhis").innerHTML="Uue kandidaadi lisamiseks logi sisse";document.getElementById("invite").style.visibility="hidden";}}
function getFBID(response){var FBID=response.authResponse.userID;var FBname=response.name;document.getElementById("FBID").value=FBID;document.getElementById("FBname").value=name;}
function createXmlHttpRequestObject(){var xmlHttp;if(window.ActiveXObject){try{xmlHttp=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){xmlHttp=false;}}else{try{xmlHttp=new XMLHttpRequest();}catch(e){xmlHttp=false;}}
if(!xmlHttp){alert("Midagi on halvasti!!");}else{return xmlHttp;}}
